import 'dotenv/config'

import mongoose from 'mongoose'

import { env } from '../config/env'
import { Car } from '../modules/car/car.model'
import { Review } from '../modules/review/review.model'

// ── helpers ───────────────────────────────────────────────────────────────────

function slug(make: string, mdl: string, variant: string, year: number) {
  return `${make}-${mdl}-${variant}-${year}`
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
}

// ── 50 Indian cars ────────────────────────────────────────────────────────────

const cars = [
  // ── Maruti Suzuki ──────────────────────────────────────────────────────────
  {
    make: 'Maruti Suzuki', model: 'Swift', variant: 'ZXi Plus', year: 2024,
    priceExShowroom: 899000, priceOnRoad: 1020000,
    bodyType: 'hatchback', segment: 'economy', fuelType: 'petrol',
    transmission: 'amt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1197, powerBhp: 89, torqueNm: 113,
    acceleration0to100Sec: 11.5, topSpeedKph: 160,
    mileageCityKmpl: 21.5, mileageHighwayKmpl: 23.2, mileageCombinedKmpl: 22.3, fuelTankLitres: 37,
    lengthMm: 3860, widthMm: 1735, heightMm: 1520, wheelbaseMm: 2450, groundClearanceMm: 163, kerbWeightKg: 895, bootSpaceLitres: 268,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Touchscreen Infotainment', 'Reverse Camera', 'Cruise Control', 'Auto AC', 'Keyless Entry', 'Push Button Start'],
    adasFeatures: [],
    tags: ['best-seller', 'fuel-efficient', 'city-car', 'first-car', 'budget'],
    popularityScore: 950, colors: ['Magma Grey', 'Sizzling Red', 'Pearl Arctic White', 'Speedy Blue'],
    images: [],
  },
  {
    make: 'Maruti Suzuki', model: 'Baleno', variant: 'Alpha', year: 2024,
    priceExShowroom: 999000, priceOnRoad: 1130000,
    bodyType: 'hatchback', segment: 'compact', fuelType: 'petrol',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1197, powerBhp: 89, torqueNm: 113,
    acceleration0to100Sec: 11.2, topSpeedKph: 165,
    mileageCityKmpl: 22.4, mileageHighwayKmpl: 23.9, mileageCombinedKmpl: 23.1, fuelTankLitres: 37,
    lengthMm: 3990, widthMm: 1745, heightMm: 1500, wheelbaseMm: 2520, groundClearanceMm: 170, kerbWeightKg: 935, bootSpaceLitres: 318,
    safetyRatingStars: 2, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['9-inch Touchscreen', 'HUD', 'Wireless CarPlay', '360 Camera', 'Auto AC', 'Sunroof'],
    adasFeatures: [],
    tags: ['premium-hatchback', 'feature-loaded', 'spacious', 'city-car'],
    popularityScore: 870, colors: ['Splendid Silver', 'Opulent Red', 'Grandeur Grey', 'Pearl Arctic White'],
    images: [],
  },
  {
    make: 'Maruti Suzuki', model: 'Grand Vitara', variant: 'Alpha Plus Strong Hybrid', year: 2024,
    priceExShowroom: 1799000, priceOnRoad: 2050000,
    bodyType: 'suv', segment: 'compact', fuelType: 'hybrid',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1490, powerBhp: 116, torqueNm: 122,
    mileageCityKmpl: 27.97, mileageHighwayKmpl: 25, mileageCombinedKmpl: 27.97, fuelTankLitres: 45,
    lengthMm: 4345, widthMm: 1795, heightMm: 1645, wheelbaseMm: 2600, groundClearanceMm: 210, kerbWeightKg: 1250, bootSpaceLitres: 373,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Panoramic Sunroof', 'Head-Up Display', '360 Camera', 'Ventilated Seats', 'Wireless Charging', '9-inch Touchscreen'],
    adasFeatures: ['Lane Departure Warning', 'Pre-Collision System'],
    tags: ['strong-hybrid', 'best-mileage', 'family-suv', 'premium'],
    popularityScore: 820, colors: ['Grandeur Grey', 'Splendid Silver', 'Opulent Red', 'Pearl Arctic White'],
    images: [],
  },
  {
    make: 'Maruti Suzuki', model: 'Brezza', variant: 'ZXi Plus', year: 2024,
    priceExShowroom: 1419000, priceOnRoad: 1610000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1462, powerBhp: 103, torqueNm: 137,
    mileageCityKmpl: 17.38, mileageHighwayKmpl: 21.7, mileageCombinedKmpl: 19.8, fuelTankLitres: 48,
    lengthMm: 3995, widthMm: 1790, heightMm: 1685, wheelbaseMm: 2500, groundClearanceMm: 210, kerbWeightKg: 1195, bootSpaceLitres: 328,
    safetyRatingStars: 4, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Sunroof', 'Wireless CarPlay', 'Auto AC', 'Cruise Control', 'Ambient Lighting', 'Heads-Up Display'],
    adasFeatures: [],
    tags: ['compact-suv', 'stylish', 'city-suv', 'first-suv'],
    popularityScore: 800, colors: ['Brave Khaki', 'Sizzling Red', 'Pearl Arctic White', 'Grandeur Grey'],
    images: [],
  },
  {
    make: 'Maruti Suzuki', model: 'Dzire', variant: 'ZXi Plus', year: 2024,
    priceExShowroom: 979000, priceOnRoad: 1115000,
    bodyType: 'sedan', segment: 'compact', fuelType: 'petrol',
    transmission: 'amt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1197, powerBhp: 89, torqueNm: 113,
    mileageCityKmpl: 23.26, mileageHighwayKmpl: 25.71, mileageCombinedKmpl: 24.1, fuelTankLitres: 37,
    lengthMm: 3995, widthMm: 1735, heightMm: 1515, wheelbaseMm: 2450, groundClearanceMm: 163, kerbWeightKg: 920, bootSpaceLitres: 378,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Touchscreen', 'Auto AC', 'Reverse Camera', 'Keyless Entry', 'Alloy Wheels'],
    adasFeatures: [],
    tags: ['compact-sedan', 'fuel-efficient', 'budget-sedan', 'cab-popular'],
    popularityScore: 780, colors: ['Magma Grey', 'Sizzling Red', 'Pearl Arctic White', 'Midnight Black'],
    images: [],
  },

  // ── Hyundai ────────────────────────────────────────────────────────────────
  {
    make: 'Hyundai', model: 'Creta', variant: 'SX(O) Turbo DCT', year: 2024,
    priceExShowroom: 2000000, priceOnRoad: 2280000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1482, powerBhp: 158, torqueNm: 253,
    acceleration0to100Sec: 8.9, topSpeedKph: 190,
    mileageCityKmpl: 14.4, mileageHighwayKmpl: 18.4, mileageCombinedKmpl: 16.8, fuelTankLitres: 50,
    lengthMm: 4330, widthMm: 1790, heightMm: 1635, wheelbaseMm: 2610, groundClearanceMm: 190, kerbWeightKg: 1440, bootSpaceLitres: 433,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Panoramic Sunroof', 'BOSE Sound', '10.25-inch Touchscreen', 'Ventilated Seats', 'Wireless Charging', 'Digital Cluster'],
    adasFeatures: ['Forward Collision Warning', 'Lane Keep Assist', 'Blind Spot Monitor', 'Driver Attention Warning'],
    tags: ['best-suv', 'premium', 'feature-loaded', 'family-suv', 'turbo'],
    popularityScore: 980, colors: ['Atlas White', 'Abyss Black', 'Titan Grey', 'Robust Emerald', 'Fiery Red'],
    images: [],
  },
  {
    make: 'Hyundai', model: 'i20', variant: 'Asta (O) Turbo DCT', year: 2024,
    priceExShowroom: 1249000, priceOnRoad: 1420000,
    bodyType: 'hatchback', segment: 'compact', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 998, powerBhp: 118, torqueNm: 172,
    acceleration0to100Sec: 9.9, topSpeedKph: 175,
    mileageCityKmpl: 17.38, mileageHighwayKmpl: 20.3, mileageCombinedKmpl: 18.6, fuelTankLitres: 37,
    lengthMm: 3995, widthMm: 1775, heightMm: 1505, wheelbaseMm: 2580, groundClearanceMm: 170, kerbWeightKg: 1110, bootSpaceLitres: 311,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2021, airbagCount: 6,
    features: ['Sunroof', 'Bose Sound', '10.25-inch Touchscreen', 'Wireless CarPlay', 'LED Headlights', 'Auto AC'],
    adasFeatures: [],
    tags: ['premium-hatchback', 'turbo', 'sporty', 'youth'],
    popularityScore: 760, colors: ['Aqua Teal', 'Fiery Red', 'Polar White', 'Starry Night'],
    images: [],
  },
  {
    make: 'Hyundai', model: 'Verna', variant: 'SX(O) Turbo DCT', year: 2024,
    priceExShowroom: 1799000, priceOnRoad: 2040000,
    bodyType: 'sedan', segment: 'mid-size', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1482, powerBhp: 158, torqueNm: 253,
    acceleration0to100Sec: 8.5, topSpeedKph: 200,
    mileageCityKmpl: 15.6, mileageHighwayKmpl: 18.5, mileageCombinedKmpl: 17.2, fuelTankLitres: 45,
    lengthMm: 4535, widthMm: 1765, heightMm: 1475, wheelbaseMm: 2670, groundClearanceMm: 165, kerbWeightKg: 1290, bootSpaceLitres: 528,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Panoramic Sunroof', 'Ventilated Seats', 'BOSE Sound', 'Digital Cluster', 'Wireless Charging', 'Auto Parking'],
    adasFeatures: ['Forward Collision Warning', 'Lane Keep Assist', 'High Beam Assist'],
    tags: ['premium-sedan', 'turbo', 'executive', 'feature-loaded'],
    popularityScore: 720, colors: ['Abyss Black', 'Atlas White', 'Titan Grey', 'Fiery Red'],
    images: [],
  },
  {
    make: 'Hyundai', model: 'Alcazar', variant: 'Platinum 7-Seater Turbo AT', year: 2024,
    priceExShowroom: 2099000, priceOnRoad: 2380000,
    bodyType: 'suv', segment: 'mid-size', fuelType: 'petrol',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 7,
    engineDisplacementCc: 1482, powerBhp: 158, torqueNm: 253,
    mileageCityKmpl: 14.2, mileageHighwayKmpl: 17.5, mileageCombinedKmpl: 16.0, fuelTankLitres: 50,
    lengthMm: 4500, widthMm: 1790, heightMm: 1675, wheelbaseMm: 2760, groundClearanceMm: 200, kerbWeightKg: 1560, bootSpaceLitres: 180,
    safetyRatingStars: 4, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Panoramic Sunroof', 'Captain Seats', 'BOSE Sound', 'Wireless Charging', 'Ventilated Seats', 'Rear AC'],
    adasFeatures: ['Forward Collision Warning', 'Lane Keep Assist'],
    tags: ['7-seater', 'family-suv', 'premium', 'spacious'],
    popularityScore: 660, colors: ['Atlas White', 'Abyss Black', 'Titan Grey'],
    images: [],
  },
  {
    make: 'Hyundai', model: 'IONIQ 5', variant: 'RWD Long Range', year: 2024,
    priceExShowroom: 4589000, priceOnRoad: 5100000,
    bodyType: 'suv', segment: 'electric', fuelType: 'electric',
    transmission: 'automatic', drivetrain: 'rwd', seatingCapacity: 5,
    powerBhp: 217, torqueNm: 350,
    acceleration0to100Sec: 7.4, topSpeedKph: 185,
    batteryKwh: 72.6, electricRangeKm: 631,
    lengthMm: 4635, widthMm: 1890, heightMm: 1605, wheelbaseMm: 3000, groundClearanceMm: 160, kerbWeightKg: 1960, bootSpaceLitres: 527,
    safetyRatingStars: 5, safetyRatingAgency: 'EURO NCAP', safetyRatingYear: 2021, airbagCount: 7,
    features: ['V2L Technology', 'Augmented Reality HUD', 'Ambient Lighting', 'Reclining Rear Seats', 'Ultra-Fast Charging', 'Wireless CarPlay'],
    adasFeatures: ['Lane Keep Assist', 'Forward Collision Avoidance', 'Blind Spot Monitoring', 'Rear Cross Traffic Alert'],
    tags: ['electric', 'ev', 'premium-ev', 'long-range', 'future'],
    popularityScore: 580, colors: ['Gravity Gold', 'Phantom Black', 'Atlas White', 'Digital Teal'],
    images: [],
  },

  // ── Tata ───────────────────────────────────────────────────────────────────
  {
    make: 'Tata', model: 'Nexon', variant: 'Creative Plus S AMT', year: 2024,
    priceExShowroom: 1479000, priceOnRoad: 1680000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'amt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1199, powerBhp: 118, torqueNm: 170,
    acceleration0to100Sec: 10.5, topSpeedKph: 175,
    mileageCityKmpl: 17.4, mileageHighwayKmpl: 20.5, mileageCombinedKmpl: 18.8, fuelTankLitres: 44,
    lengthMm: 3993, widthMm: 1811, heightMm: 1606, wheelbaseMm: 2498, groundClearanceMm: 208, kerbWeightKg: 1240, bootSpaceLitres: 350,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Sunroof', 'JBL Sound', '10.25-inch Touchscreen', 'Air Purifier', 'Wireless Charging', 'Auto AC'],
    adasFeatures: ['Forward Collision Warning', 'Lane Departure Warning', 'Traffic Sign Recognition'],
    tags: ['5-star-safety', 'compact-suv', 'safest-car', 'value-for-money'],
    popularityScore: 910, colors: ['Pristine White', 'Daytona Grey', 'Flame Red', 'Foliage Green', 'Fearless Purple'],
    images: [],
  },
  {
    make: 'Tata', model: 'Nexon EV', variant: 'Max Creative Plus LR', year: 2024,
    priceExShowroom: 1999000, priceOnRoad: 2280000,
    bodyType: 'suv', segment: 'electric', fuelType: 'electric',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    powerBhp: 143, torqueNm: 250,
    acceleration0to100Sec: 8.9, topSpeedKph: 150,
    batteryKwh: 40.5, electricRangeKm: 465,
    lengthMm: 3993, widthMm: 1811, heightMm: 1616, wheelbaseMm: 2498, groundClearanceMm: 208, kerbWeightKg: 1490, bootSpaceLitres: 350,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['10.25-inch Touchscreen', 'JBL Sound', 'Sunroof', 'Air Purifier', 'V2L', 'Wireless Charging'],
    adasFeatures: ['Forward Collision Warning', 'Lane Departure Warning'],
    tags: ['electric', 'best-selling-ev', 'compact-suv', 'safe-ev'],
    popularityScore: 870, colors: ['Pristine White', 'Daytona Grey', 'Flame Red', 'Intensi-Teal'],
    images: [],
  },
  {
    make: 'Tata', model: 'Punch', variant: 'Accomplished Plus S AMT', year: 2024,
    priceExShowroom: 999000, priceOnRoad: 1130000,
    bodyType: 'suv', segment: 'economy', fuelType: 'petrol',
    transmission: 'amt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1199, powerBhp: 86, torqueNm: 113,
    mileageCityKmpl: 18.97, mileageHighwayKmpl: 21.3, mileageCombinedKmpl: 20.1, fuelTankLitres: 40,
    lengthMm: 3827, widthMm: 1742, heightMm: 1615, wheelbaseMm: 2445, groundClearanceMm: 187, kerbWeightKg: 1055, bootSpaceLitres: 366,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2021, airbagCount: 2,
    features: ['7-inch Touchscreen', 'Auto AC', 'Reverse Camera', 'Wireless CarPlay', 'LED DRLs'],
    adasFeatures: [],
    tags: ['micro-suv', '5-star-safety', 'budget-suv', 'first-suv'],
    popularityScore: 850, colors: ['Orcus White', 'Meteor Bronze', 'Daytona Grey', 'Flame Red'],
    images: [],
  },
  {
    make: 'Tata', model: 'Harrier', variant: 'Adventure Plus Dark AT', year: 2024,
    priceExShowroom: 2399000, priceOnRoad: 2720000,
    bodyType: 'suv', segment: 'mid-size', fuelType: 'diesel',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1956, powerBhp: 168, torqueNm: 350,
    acceleration0to100Sec: 10.1, topSpeedKph: 180,
    mileageCityKmpl: 14.6, mileageHighwayKmpl: 17.8, mileageCombinedKmpl: 16.35, fuelTankLitres: 50,
    lengthMm: 4598, widthMm: 1894, heightMm: 1706, wheelbaseMm: 2741, groundClearanceMm: 205, kerbWeightKg: 1790, bootSpaceLitres: 425,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Panoramic Sunroof', 'JBL Sound', '10.25-inch Touchscreen', 'Ventilated Seats', 'Air Purifier', 'Wireless Charging'],
    adasFeatures: ['Forward Collision Warning', 'Lane Keep Assist', 'Blind Spot Monitor', 'Auto Emergency Braking'],
    tags: ['premium-suv', 'diesel', 'family-suv', 'safe', 'spacious'],
    popularityScore: 790, colors: ['Orcus White', 'Oberon Black', 'Lunar Slate', 'Daytona Grey'],
    images: [],
  },
  {
    make: 'Tata', model: 'Safari', variant: 'Adventure Plus Dark 7S AT', year: 2024,
    priceExShowroom: 2599000, priceOnRoad: 2950000,
    bodyType: 'suv', segment: 'mid-size', fuelType: 'diesel',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 7,
    engineDisplacementCc: 1956, powerBhp: 168, torqueNm: 350,
    mileageCityKmpl: 14.3, mileageHighwayKmpl: 17.5, mileageCombinedKmpl: 16.1, fuelTankLitres: 50,
    lengthMm: 4661, widthMm: 1894, heightMm: 1786, wheelbaseMm: 2741, groundClearanceMm: 205, kerbWeightKg: 1895, bootSpaceLitres: 73,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 7,
    features: ['Panoramic Sunroof', 'JBL Sound', '10.25-inch Touchscreen', 'Captain Seats', 'Ventilated Seats', 'Wireless Charging'],
    adasFeatures: ['Forward Collision Warning', 'Lane Keep Assist', 'Blind Spot Monitor'],
    tags: ['7-seater', 'family-suv', 'safe', 'premium-diesel'],
    popularityScore: 750, colors: ['Orcus White', 'Oberon Black', 'Tropical Mist', 'Daytona Grey'],
    images: [],
  },

  // ── Honda ──────────────────────────────────────────────────────────────────
  {
    make: 'Honda', model: 'City', variant: 'ZX CVT', year: 2024,
    priceExShowroom: 1649000, priceOnRoad: 1870000,
    bodyType: 'sedan', segment: 'mid-size', fuelType: 'petrol',
    transmission: 'cvt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1498, powerBhp: 121, torqueNm: 145,
    acceleration0to100Sec: 10.4, topSpeedKph: 185,
    mileageCityKmpl: 16.5, mileageHighwayKmpl: 18.2, mileageCombinedKmpl: 17.4, fuelTankLitres: 40,
    lengthMm: 4553, widthMm: 1748, heightMm: 1489, wheelbaseMm: 2600, groundClearanceMm: 165, kerbWeightKg: 1214, bootSpaceLitres: 506,
    safetyRatingStars: 4, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['Sunroof', '8-inch Touchscreen', 'Honda Sensing', 'Wireless CarPlay', 'Auto AC', 'Remote Engine Start'],
    adasFeatures: ['Collision Mitigation Braking', 'Lane Keep Assist', 'Auto High Beam', 'Road Departure Mitigation'],
    tags: ['premium-sedan', 'reliable', 'executive', 'comfort'],
    popularityScore: 730, colors: ['Platinum White Pearl', 'Lunar Silver', 'Meteoroid Grey', 'Radiant Red'],
    images: [],
  },
  {
    make: 'Honda', model: 'Elevate', variant: 'ZX CVT', year: 2024,
    priceExShowroom: 1749000, priceOnRoad: 1990000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'cvt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1498, powerBhp: 121, torqueNm: 145,
    mileageCityKmpl: 15.3, mileageHighwayKmpl: 17.8, mileageCombinedKmpl: 16.9, fuelTankLitres: 40,
    lengthMm: 4312, widthMm: 1790, heightMm: 1650, wheelbaseMm: 2650, groundClearanceMm: 220, kerbWeightKg: 1340, bootSpaceLitres: 458,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Sunroof', '10.25-inch Touchscreen', 'Honda Sensing', 'Wireless Charging', 'Ventilated Seats', 'Air Purifier'],
    adasFeatures: ['Collision Mitigation', 'Lane Keep Assist', 'Auto High Beam'],
    tags: ['compact-suv', 'safe', 'premium', 'honda-reliability'],
    popularityScore: 700, colors: ['Platinum White Pearl', 'Lunar Silver', 'Meteoroid Grey', 'Sonic Grey'],
    images: [],
  },

  // ── Toyota ─────────────────────────────────────────────────────────────────
  {
    make: 'Toyota', model: 'Fortuner', variant: 'Legender 4x4 AT', year: 2024,
    priceExShowroom: 4699000, priceOnRoad: 5300000,
    bodyType: 'suv', segment: 'full-size', fuelType: 'diesel',
    transmission: 'automatic', drivetrain: '4wd', seatingCapacity: 7,
    engineDisplacementCc: 2755, powerBhp: 201, torqueNm: 500,
    acceleration0to100Sec: 9.5, topSpeedKph: 180,
    mileageCityKmpl: 10.0, mileageHighwayKmpl: 14.2, mileageCombinedKmpl: 12.0, fuelTankLitres: 80,
    lengthMm: 4795, widthMm: 1855, heightMm: 1835, wheelbaseMm: 2745, groundClearanceMm: 279, kerbWeightKg: 2225, bootSpaceLitres: 296,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 7,
    features: ['Panoramic View Monitor', 'JBL Sound', '8-inch Touchscreen', 'Wireless Charging', 'Sunroof', 'Terrain Management'],
    adasFeatures: ['Pre-Collision System', 'Lane Departure Alert', 'Automatic High Beam'],
    tags: ['full-size-suv', '4x4', 'off-road', 'premium', 'powerful'],
    popularityScore: 850, colors: ['Super White', 'Attitude Black', 'Silver Metallic', 'Dark Brown Mica'],
    images: [],
  },
  {
    make: 'Toyota', model: 'Innova Hycross', variant: 'VX HEV CVT 7S', year: 2024,
    priceExShowroom: 2999000, priceOnRoad: 3400000,
    bodyType: 'minivan', segment: 'mid-size', fuelType: 'hybrid',
    transmission: 'cvt', drivetrain: 'fwd', seatingCapacity: 7,
    engineDisplacementCc: 1987, powerBhp: 186, torqueNm: 188,
    mileageCityKmpl: 21.1, mileageHighwayKmpl: 23.4, mileageCombinedKmpl: 21.1, fuelTankLitres: 52,
    lengthMm: 4755, widthMm: 1850, heightMm: 1795, wheelbaseMm: 2850, groundClearanceMm: 185, kerbWeightKg: 1985, bootSpaceLitres: 213,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 7,
    features: ['Panoramic Sunroof', 'JBL Sound', '10.1-inch Touchscreen', 'Captain Seats', 'Wireless Charging', 'Rear Entertainment'],
    adasFeatures: ['Pre-Collision System', 'Lane Departure Alert', 'Radar Cruise Control'],
    tags: ['hybrid', 'best-mileage-mpv', 'family', '7-seater', 'premium-mpv'],
    popularityScore: 820, colors: ['Super White', 'Silver Metallic', 'Attitude Black', 'Phantom Brown'],
    images: [],
  },
  {
    make: 'Toyota', model: 'Urban Cruiser Hyryder', variant: 'V Strong Hybrid E-CVT', year: 2024,
    priceExShowroom: 1899000, priceOnRoad: 2160000,
    bodyType: 'suv', segment: 'compact', fuelType: 'hybrid',
    transmission: 'cvt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1490, powerBhp: 116, torqueNm: 122,
    mileageCityKmpl: 27.97, mileageHighwayKmpl: 25.0, mileageCombinedKmpl: 27.97, fuelTankLitres: 36,
    lengthMm: 4365, widthMm: 1795, heightMm: 1635, wheelbaseMm: 2600, groundClearanceMm: 210, kerbWeightKg: 1270, bootSpaceLitres: 373,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Panoramic Sunroof', 'Head-Up Display', '9-inch Touchscreen', 'Ventilated Seats', 'Wireless Charging', '360 View Camera'],
    adasFeatures: ['Pre-Collision System', 'Lane Departure Alert'],
    tags: ['strong-hybrid', 'best-mileage', 'compact-suv', 'eco'],
    popularityScore: 730, colors: ['Cafe White', 'Sporting Red', 'Midnight Black', 'Enticing Silver'],
    images: [],
  },

  // ── Kia ────────────────────────────────────────────────────────────────────
  {
    make: 'Kia', model: 'Seltos', variant: 'X Line GT DCT AWD', year: 2024,
    priceExShowroom: 2099000, priceOnRoad: 2380000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'awd', seatingCapacity: 5,
    engineDisplacementCc: 1482, powerBhp: 158, torqueNm: 253,
    acceleration0to100Sec: 8.5, topSpeedKph: 195,
    mileageCityKmpl: 13.2, mileageHighwayKmpl: 16.5, mileageCombinedKmpl: 14.8, fuelTankLitres: 50,
    lengthMm: 4370, widthMm: 1800, heightMm: 1640, wheelbaseMm: 2610, groundClearanceMm: 190, kerbWeightKg: 1520, bootSpaceLitres: 433,
    safetyRatingStars: 4, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['Panoramic Sunroof', 'Bose Sound', '10.25-inch Touchscreen', 'AWD', 'Ventilated Seats', 'Wireless Charging'],
    adasFeatures: ['Forward Collision Warning', 'Lane Keep Assist', 'Blind Spot Monitor', 'Rear Cross Traffic Alert'],
    tags: ['awd', 'turbo', 'compact-suv', 'sporty', 'feature-loaded'],
    popularityScore: 880, colors: ['Imperial Blue', 'Matte Graphite', 'Aurora Black Pearl', 'Glacier White'],
    images: [],
  },
  {
    make: 'Kia', model: 'Carens', variant: 'Luxury Plus 7S DCT', year: 2024,
    priceExShowroom: 1899000, priceOnRoad: 2150000,
    bodyType: 'minivan', segment: 'mid-size', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 7,
    engineDisplacementCc: 1482, powerBhp: 158, torqueNm: 253,
    mileageCityKmpl: 14.5, mileageHighwayKmpl: 17.8, mileageCombinedKmpl: 16.3, fuelTankLitres: 45,
    lengthMm: 4540, widthMm: 1800, heightMm: 1708, wheelbaseMm: 2780, groundClearanceMm: 195, kerbWeightKg: 1540, bootSpaceLitres: 216,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Panoramic Sunroof', 'Bose Sound', '10.25-inch Touchscreen', 'Captain Seats', 'Ventilated Seats', 'Rear AC Vents'],
    adasFeatures: ['Forward Collision Warning', 'Lane Keep Assist'],
    tags: ['7-seater', 'family-mpv', 'spacious', 'premium-mpv', 'turbo'],
    popularityScore: 700, colors: ['Gravity Grey', 'Imperial Blue', 'Aurora Black', 'Glacier White'],
    images: [],
  },
  {
    make: 'Kia', model: 'EV6', variant: 'GT Line AWD', year: 2024,
    priceExShowroom: 6099000, priceOnRoad: 6800000,
    bodyType: 'crossover', segment: 'electric', fuelType: 'electric',
    transmission: 'automatic', drivetrain: 'awd', seatingCapacity: 5,
    powerBhp: 320, torqueNm: 605,
    acceleration0to100Sec: 5.1, topSpeedKph: 185,
    batteryKwh: 77.4, electricRangeKm: 506,
    lengthMm: 4695, widthMm: 1890, heightMm: 1550, wheelbaseMm: 2900, groundClearanceMm: 160, kerbWeightKg: 2100, bootSpaceLitres: 480,
    safetyRatingStars: 5, safetyRatingAgency: 'EURO NCAP', safetyRatingYear: 2021, airbagCount: 7,
    features: ['V2L Technology', 'Panoramic Glass Roof', 'Digital Cockpit', 'Meridian Sound', 'Ultra-Fast 800V Charging', 'Head-Up Display'],
    adasFeatures: ['Forward Collision Avoidance', 'Lane Keep Assist', 'Blind Spot Collision Avoidance', 'Rear Cross-Traffic Avoidance'],
    tags: ['electric', 'awd', 'premium-ev', 'performance-ev', 'future'],
    popularityScore: 540, colors: ['Runway Red', 'Moonscape', 'Glacier', 'Yacht Blue'],
    images: [],
  },

  // ── MG ─────────────────────────────────────────────────────────────────────
  {
    make: 'MG', model: 'Hector', variant: 'Select Pro CVT', year: 2024,
    priceExShowroom: 1999000, priceOnRoad: 2270000,
    bodyType: 'suv', segment: 'mid-size', fuelType: 'petrol',
    transmission: 'cvt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1451, powerBhp: 140, torqueNm: 250,
    mileageCityKmpl: 14.8, mileageHighwayKmpl: 17.1, mileageCombinedKmpl: 15.8, fuelTankLitres: 60,
    lengthMm: 4720, widthMm: 1835, heightMm: 1760, wheelbaseMm: 2750, groundClearanceMm: 192, kerbWeightKg: 1740, bootSpaceLitres: 587,
    safetyRatingStars: 4, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['14-inch Touchscreen', 'Panoramic Sunroof', 'Connected Car Tech', 'BOSE Sound', 'Wireless Charging', 'Auto Park Assist'],
    adasFeatures: ['Forward Collision Warning', 'Lane Change Assist', 'Traffic Sign Recognition'],
    tags: ['large-suv', 'connected-car', 'feature-loaded', 'spacious'],
    popularityScore: 690, colors: ['Candy White', 'Starry Black', 'Burgundy Red', 'Aurora Silver'],
    images: [],
  },
  {
    make: 'MG', model: 'Windsor EV', variant: 'Excite Plus', year: 2024,
    priceExShowroom: 1399000, priceOnRoad: 1580000,
    bodyType: 'crossover', segment: 'electric', fuelType: 'electric',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    powerBhp: 134, torqueNm: 200,
    acceleration0to100Sec: 8.5, topSpeedKph: 160,
    batteryKwh: 38, electricRangeKm: 331,
    lengthMm: 4295, widthMm: 1850, heightMm: 1677, wheelbaseMm: 2700, groundClearanceMm: 170, kerbWeightKg: 1570, bootSpaceLitres: 604,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2024, airbagCount: 6,
    features: ['14.5-inch Touchscreen', 'Panoramic Glass Roof', 'Wireless Charging', 'Connected Car', 'Ambient Lighting', 'Ventilated Seats'],
    adasFeatures: ['Forward Collision Warning', 'Blind Spot Detection'],
    tags: ['electric', 'affordable-ev', 'city-ev', 'value-ev'],
    popularityScore: 720, colors: ['Starry Black', 'Candy White', 'Aurora Silver', 'Turquoise'],
    images: [],
  },
  {
    make: 'MG', model: 'Comet EV', variant: 'Excite', year: 2024,
    priceExShowroom: 699000, priceOnRoad: 790000,
    bodyType: 'hatchback', segment: 'electric', fuelType: 'electric',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 4,
    powerBhp: 42, torqueNm: 110,
    acceleration0to100Sec: 13.0, topSpeedKph: 100,
    batteryKwh: 17.3, electricRangeKm: 230,
    lengthMm: 2974, widthMm: 1505, heightMm: 1640, wheelbaseMm: 2010, groundClearanceMm: 165, kerbWeightKg: 895, bootSpaceLitres: 63,
    safetyRatingStars: 1, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2024, airbagCount: 2,
    features: ['10.25-inch Touchscreen', 'Connected Car', 'Auto AC', 'Keyless Entry'],
    adasFeatures: [],
    tags: ['micro-ev', 'city-commuter', 'cheapest-ev', 'electric'],
    popularityScore: 560, colors: ['Bubblegum Blue', 'Candy White', 'Starry Black', 'Yellow'],
    images: [],
  },

  // ── Mahindra ───────────────────────────────────────────────────────────────
  {
    make: 'Mahindra', model: 'Scorpio N', variant: 'Z8 L AT 4WD', year: 2024,
    priceExShowroom: 2399000, priceOnRoad: 2720000,
    bodyType: 'suv', segment: 'mid-size', fuelType: 'diesel',
    transmission: 'automatic', drivetrain: '4wd', seatingCapacity: 7,
    engineDisplacementCc: 2184, powerBhp: 175, torqueNm: 400,
    acceleration0to100Sec: 10.8, topSpeedKph: 180,
    mileageCityKmpl: 13.6, mileageHighwayKmpl: 16.9, mileageCombinedKmpl: 15.2, fuelTankLitres: 60,
    lengthMm: 4662, widthMm: 1917, heightMm: 1857, wheelbaseMm: 2750, groundClearanceMm: 200, kerbWeightKg: 2100, bootSpaceLitres: 160,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 6,
    features: ['Sony Sound', 'Dual-Zone Climate Control', 'Wireless Charging', 'AdrenoX', 'Drive Modes', 'Terrain Management'],
    adasFeatures: ['Forward Collision Warning', 'Blind Spot Monitor', 'Lane Change Warning'],
    tags: ['4wd', 'off-road', 'powerful-diesel', 'family-suv', 'rugged'],
    popularityScore: 860, colors: ['Deep Forest', 'Dune', 'Grand White', 'Burnt Sienna', 'Napoli Black'],
    images: [],
  },
  {
    make: 'Mahindra', model: 'XUV 3XO', variant: 'AX7 L AT Turbo', year: 2024,
    priceExShowroom: 1699000, priceOnRoad: 1930000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1197, powerBhp: 130, torqueNm: 230,
    mileageCityKmpl: 17.96, mileageHighwayKmpl: 20.2, mileageCombinedKmpl: 18.8, fuelTankLitres: 40,
    lengthMm: 3990, widthMm: 1821, heightMm: 1647, wheelbaseMm: 2600, groundClearanceMm: 201, kerbWeightKg: 1270, bootSpaceLitres: 364,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2024, airbagCount: 6,
    features: ['Panoramic Sunroof', 'Sony Sound', 'AdrenoX Infotainment', 'ADAS Level 2', 'Wireless Charging', 'Ventilated Seats'],
    adasFeatures: ['Adaptive Cruise Control', 'Lane Centering', 'Forward Collision Warning', 'Auto Emergency Braking', 'Blind Spot Monitor'],
    tags: ['compact-suv', 'adas-level2', '5-star-safety', 'feature-rich'],
    popularityScore: 810, colors: ['Everest White', 'Nebula Blue', 'Tango Red', 'Stealth Black'],
    images: [],
  },
  {
    make: 'Mahindra', model: 'XUV700', variant: 'AX7 L AT AWD', year: 2024,
    priceExShowroom: 2599000, priceOnRoad: 2950000,
    bodyType: 'suv', segment: 'mid-size', fuelType: 'petrol',
    transmission: 'automatic', drivetrain: 'awd', seatingCapacity: 7,
    engineDisplacementCc: 1997, powerBhp: 197, torqueNm: 380,
    acceleration0to100Sec: 8.5, topSpeedKph: 200,
    mileageCityKmpl: 13.3, mileageHighwayKmpl: 16.8, mileageCombinedKmpl: 14.9, fuelTankLitres: 60,
    lengthMm: 4695, widthMm: 1890, heightMm: 1755, wheelbaseMm: 2750, groundClearanceMm: 207, kerbWeightKg: 1945, bootSpaceLitres: 195,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 7,
    features: ['Panoramic Sunroof', 'Sony Sound', 'ADAS Level 2', 'Wireless Charging', 'SmartPilot Assist', 'Night Vision'],
    adasFeatures: ['Adaptive Cruise Control', 'Auto Emergency Braking', 'Lane Keep Assist', 'Blind Spot Monitor', 'Night Vision Alert'],
    tags: ['7-seater', 'awd', 'adas-level2', 'premium-suv', 'powerful'],
    popularityScore: 890, colors: ['Midnight Black', 'Burnt Sienna', 'Electric Blue', 'Grand White'],
    images: [],
  },
  {
    make: 'Mahindra', model: 'Thar Roxx', variant: 'MX5 AT AWD Diesel', year: 2024,
    priceExShowroom: 1849000, priceOnRoad: 2100000,
    bodyType: 'suv', segment: 'mid-size', fuelType: 'diesel',
    transmission: 'automatic', drivetrain: '4wd', seatingCapacity: 5,
    engineDisplacementCc: 2184, powerBhp: 175, torqueNm: 370,
    mileageCityKmpl: 15.2, mileageHighwayKmpl: 18.9, mileageCombinedKmpl: 16.8, fuelTankLitres: 57,
    lengthMm: 4428, widthMm: 1870, heightMm: 1900, wheelbaseMm: 2850, groundClearanceMm: 226, kerbWeightKg: 1950, bootSpaceLitres: 330,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2024, airbagCount: 7,
    features: ['10.25-inch Touchscreen', 'Sony Sound', 'Wireless Charging', 'Terrain Management', 'Sway Control', 'Hill Descent Control'],
    adasFeatures: ['Forward Collision Warning', 'Lane Change Warning', 'Blind Spot Monitor'],
    tags: ['4wd', 'off-road', 'adventure', 'rugged', '5-star-safety'],
    popularityScore: 830, colors: ['Tango Red', 'Stealth Black', 'Everest White', 'Desert Dust'],
    images: [],
  },

  // ── Volkswagen ─────────────────────────────────────────────────────────────
  {
    make: 'Volkswagen', model: 'Virtus', variant: 'GT Plus DSG', year: 2024,
    priceExShowroom: 1749000, priceOnRoad: 1980000,
    bodyType: 'sedan', segment: 'mid-size', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1498, powerBhp: 148, torqueNm: 250,
    acceleration0to100Sec: 8.5, topSpeedKph: 200,
    mileageCityKmpl: 15.6, mileageHighwayKmpl: 19.4, mileageCombinedKmpl: 17.5, fuelTankLitres: 55,
    lengthMm: 4561, widthMm: 1752, heightMm: 1507, wheelbaseMm: 2651, groundClearanceMm: 179, kerbWeightKg: 1250, bootSpaceLitres: 521,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['10.1-inch Touchscreen', 'Wireless CarPlay', 'Auto AC', 'Ventilated Seats', 'Ambient Lighting', 'Cruise Control'],
    adasFeatures: ['Front Assist', 'Lane Assist', 'Blind Spot Monitoring', 'Rear Traffic Alert'],
    tags: ['sedan', 'german-engineering', 'sporty-sedan', 'turbo', 'build-quality'],
    popularityScore: 680, colors: ['Curcuma Yellow', 'Candy White', 'Lapiz Blue', 'Silver', 'Black'],
    images: [],
  },
  {
    make: 'Volkswagen', model: 'Taigun', variant: 'GT Plus DSG', year: 2024,
    priceExShowroom: 1899000, priceOnRoad: 2150000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1498, powerBhp: 148, torqueNm: 250,
    acceleration0to100Sec: 8.9, topSpeedKph: 190,
    mileageCityKmpl: 14.4, mileageHighwayKmpl: 17.8, mileageCombinedKmpl: 16.2, fuelTankLitres: 50,
    lengthMm: 4221, widthMm: 1760, heightMm: 1612, wheelbaseMm: 2651, groundClearanceMm: 188, kerbWeightKg: 1230, bootSpaceLitres: 385,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['10.1-inch Touchscreen', 'Wireless CarPlay', 'Ventilated Seats', 'Ambient Lighting', 'Auto AC', 'Sunroof'],
    adasFeatures: ['Front Assist', 'Lane Assist', 'Blind Spot Monitor'],
    tags: ['compact-suv', 'german-engineering', 'turbo', 'sporty'],
    popularityScore: 660, colors: ['Curcuma Yellow', 'Candy White', 'Lapiz Blue', 'Carbon Steel'],
    images: [],
  },

  // ── Skoda ──────────────────────────────────────────────────────────────────
  {
    make: 'Skoda', model: 'Slavia', variant: 'Style TSI DSG', year: 2024,
    priceExShowroom: 1749000, priceOnRoad: 1980000,
    bodyType: 'sedan', segment: 'mid-size', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1498, powerBhp: 148, torqueNm: 250,
    acceleration0to100Sec: 8.6, topSpeedKph: 200,
    mileageCityKmpl: 15.4, mileageHighwayKmpl: 19.7, mileageCombinedKmpl: 17.5, fuelTankLitres: 55,
    lengthMm: 4541, widthMm: 1752, heightMm: 1487, wheelbaseMm: 2651, groundClearanceMm: 179, kerbWeightKg: 1250, bootSpaceLitres: 521,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['10-inch Touchscreen', 'Wireless CarPlay', 'Auto AC', 'Ventilated Seats', 'Wireless Charging', 'Ambient Lighting'],
    adasFeatures: ['Front Assist', 'Lane Assist', 'Blind Spot Monitor'],
    tags: ['sedan', 'czech-engineering', 'turbo', 'spacious-boot', 'build-quality'],
    popularityScore: 620, colors: ['Candy White', 'Steel Grey', 'Race Blue', 'Carbon Steel'],
    images: [],
  },
  {
    make: 'Skoda', model: 'Kushaq', variant: 'Style TSI DSG', year: 2024,
    priceExShowroom: 1799000, priceOnRoad: 2040000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1498, powerBhp: 148, torqueNm: 250,
    mileageCityKmpl: 14.2, mileageHighwayKmpl: 17.6, mileageCombinedKmpl: 16.1, fuelTankLitres: 50,
    lengthMm: 4225, widthMm: 1760, heightMm: 1612, wheelbaseMm: 2651, groundClearanceMm: 188, kerbWeightKg: 1245, bootSpaceLitres: 385,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['10-inch Touchscreen', 'Wireless CarPlay', 'Ventilated Seats', 'Sunroof', 'Ambient Lighting', 'Auto AC'],
    adasFeatures: ['Front Assist', 'Lane Assist', 'Blind Spot Monitor'],
    tags: ['compact-suv', 'czech-engineering', 'turbo', 'sporty', 'build-quality'],
    popularityScore: 600, colors: ['Candy White', 'Tornado Red', 'Brilliant Silver', 'Honey Orange'],
    images: [],
  },

  // ── Jeep ───────────────────────────────────────────────────────────────────
  {
    make: 'Jeep', model: 'Meridian', variant: '4x4 Limited Diesel AT', year: 2024,
    priceExShowroom: 3999000, priceOnRoad: 4520000,
    bodyType: 'suv', segment: 'full-size', fuelType: 'diesel',
    transmission: 'automatic', drivetrain: '4wd', seatingCapacity: 7,
    engineDisplacementCc: 1956, powerBhp: 197, torqueNm: 450,
    acceleration0to100Sec: 9.1, topSpeedKph: 190,
    mileageCityKmpl: 11.8, mileageHighwayKmpl: 15.5, mileageCombinedKmpl: 13.4, fuelTankLitres: 61,
    lengthMm: 4769, widthMm: 1869, heightMm: 1696, wheelbaseMm: 2794, groundClearanceMm: 202, kerbWeightKg: 1966, bootSpaceLitres: 232,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 7,
    features: ['McIntosh Sound', 'Meridian Mode Selector', 'Park Assist', 'Wireless Charging', '10.25-inch Touchscreen', 'Ventilated Seats'],
    adasFeatures: ['Adaptive Cruise Control', 'Forward Collision Warning', 'Blind Spot Monitoring', 'Lane Keep Assist'],
    tags: ['4wd', 'off-road', '7-seater', 'premium-suv', 'american'],
    popularityScore: 520, colors: ['White', 'Black', 'Blue', 'Red'],
    images: [],
  },

  // ── Nissan ─────────────────────────────────────────────────────────────────
  {
    make: 'Nissan', model: 'Magnite', variant: 'Turbo CVT XV Premium', year: 2024,
    priceExShowroom: 1099000, priceOnRoad: 1250000,
    bodyType: 'suv', segment: 'economy', fuelType: 'petrol',
    transmission: 'cvt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 999, powerBhp: 99, torqueNm: 160,
    mileageCityKmpl: 17.7, mileageHighwayKmpl: 20.4, mileageCombinedKmpl: 18.8, fuelTankLitres: 40,
    lengthMm: 3994, widthMm: 1758, heightMm: 1572, wheelbaseMm: 2500, groundClearanceMm: 205, kerbWeightKg: 1095, bootSpaceLitres: 336,
    safetyRatingStars: 4, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['8-inch Touchscreen', 'Wireless CarPlay', 'Auto AC', 'Ambient Lighting', 'Wireless Charging', 'Sunroof'],
    adasFeatures: [],
    tags: ['budget-suv', 'turbo', 'compact-suv', 'first-suv', 'value'],
    popularityScore: 650, colors: ['Vivid Blue', 'Blade Silver', 'Storm White', 'Black', 'Red'],
    images: [],
  },

  // ── Renault ────────────────────────────────────────────────────────────────
  {
    make: 'Renault', model: 'Kiger', variant: 'RXZ Turbo CVT', year: 2024,
    priceExShowroom: 1099000, priceOnRoad: 1250000,
    bodyType: 'suv', segment: 'economy', fuelType: 'petrol',
    transmission: 'cvt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 999, powerBhp: 99, torqueNm: 160,
    mileageCityKmpl: 18.2, mileageHighwayKmpl: 21.4, mileageCombinedKmpl: 19.6, fuelTankLitres: 40,
    lengthMm: 3991, widthMm: 1752, heightMm: 1600, wheelbaseMm: 2500, groundClearanceMm: 205, kerbWeightKg: 1050, bootSpaceLitres: 405,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 4,
    features: ['8-inch Touchscreen', 'Wireless CarPlay', 'Auto AC', 'LED Headlights', 'Wireless Charging'],
    adasFeatures: [],
    tags: ['budget-suv', 'large-boot', 'french-car', 'compact-suv', 'value'],
    popularityScore: 580, colors: ['Cedar Brown', 'Moonlight Silver', 'Ice Cool White', 'Flame Red'],
    images: [],
  },

  // ── Citroen ────────────────────────────────────────────────────────────────
  {
    make: 'Citroen', model: 'Basalt', variant: 'Shine Plus Turbo AT', year: 2024,
    priceExShowroom: 1299000, priceOnRoad: 1480000,
    bodyType: 'suv', segment: 'compact', fuelType: 'petrol',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1199, powerBhp: 110, torqueNm: 190,
    mileageCityKmpl: 17.5, mileageHighwayKmpl: 20.8, mileageCombinedKmpl: 18.9, fuelTankLitres: 45,
    lengthMm: 4352, widthMm: 1765, heightMm: 1593, wheelbaseMm: 2651, groundClearanceMm: 180, kerbWeightKg: 1250, bootSpaceLitres: 470,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2024, airbagCount: 6,
    features: ['10.25-inch Touchscreen', 'Wireless CarPlay', 'Auto AC', 'Panoramic Sunroof', 'Wireless Charging'],
    adasFeatures: [],
    tags: ['french-car', 'coupe-suv', 'stylish', 'compact-suv'],
    popularityScore: 490, colors: ['Moonlit Silver', 'Pearl White', 'Hurricane Grey', 'Fire Red'],
    images: [],
  },

  // ── BMW / Mercedes / Audi (luxury) ─────────────────────────────────────────
  {
    make: 'BMW', model: '3 Series', variant: '330i M Sport', year: 2024,
    priceExShowroom: 6499000, priceOnRoad: 7300000,
    bodyType: 'sedan', segment: 'luxury', fuelType: 'petrol',
    transmission: 'automatic', drivetrain: 'rwd', seatingCapacity: 5,
    engineDisplacementCc: 1998, powerBhp: 255, torqueNm: 400,
    acceleration0to100Sec: 5.8, topSpeedKph: 250,
    mileageCityKmpl: 11.5, mileageHighwayKmpl: 14.8, mileageCombinedKmpl: 13.2, fuelTankLitres: 59,
    lengthMm: 4713, widthMm: 1827, heightMm: 1435, wheelbaseMm: 2851, groundClearanceMm: 140, kerbWeightKg: 1535, bootSpaceLitres: 480,
    safetyRatingStars: 5, safetyRatingAgency: 'EURO NCAP', safetyRatingYear: 2022, airbagCount: 8,
    features: ['BMW Curved Display', 'Harman Kardon Sound', 'Ambient Lighting', 'Ventilated Seats', 'Wireless Charging', 'Panoramic Sunroof'],
    adasFeatures: ['Active Cruise Control', 'Lane Departure Warning', 'Blind Spot Detection', 'Parking Assistant Plus'],
    tags: ['luxury-sedan', 'german-luxury', 'sports-sedan', 'executive', 'premium'],
    popularityScore: 700, colors: ['Alpine White', 'Mineral Grey', 'San Remo Green', 'Sapphire Black'],
    images: [],
  },
  {
    make: 'Mercedes-Benz', model: 'C-Class', variant: 'C 220d AMG Line', year: 2024,
    priceExShowroom: 6799000, priceOnRoad: 7650000,
    bodyType: 'sedan', segment: 'luxury', fuelType: 'diesel',
    transmission: 'automatic', drivetrain: 'rwd', seatingCapacity: 5,
    engineDisplacementCc: 1992, powerBhp: 197, torqueNm: 440,
    acceleration0to100Sec: 7.3, topSpeedKph: 240,
    mileageCityKmpl: 13.5, mileageHighwayKmpl: 17.8, mileageCombinedKmpl: 15.5, fuelTankLitres: 66,
    lengthMm: 4751, widthMm: 1820, heightMm: 1437, wheelbaseMm: 2865, groundClearanceMm: 142, kerbWeightKg: 1640, bootSpaceLitres: 455,
    safetyRatingStars: 5, safetyRatingAgency: 'EURO NCAP', safetyRatingYear: 2022, airbagCount: 8,
    features: ['11.9-inch OLED Display', 'Burmester Sound', 'Ambient Lighting 64-colour', 'MBUX Navigation', 'Panoramic Sunroof', 'Wireless Charging'],
    adasFeatures: ['Active Brake Assist', 'Adaptive Highbeam', 'Lane Keep Assist', 'Parking Package'],
    tags: ['luxury-sedan', 'prestige', 'german-luxury', 'diesel-luxury', 'executive'],
    popularityScore: 720, colors: ['Obsidian Black', 'Mojave Silver', 'High-Tech Silver', 'Polar White'],
    images: [],
  },
  {
    make: 'Audi', model: 'Q3', variant: '45 TFSI Premium Plus Quattro', year: 2024,
    priceExShowroom: 4999000, priceOnRoad: 5600000,
    bodyType: 'suv', segment: 'luxury', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'awd', seatingCapacity: 5,
    engineDisplacementCc: 1984, powerBhp: 230, torqueNm: 350,
    acceleration0to100Sec: 6.3, topSpeedKph: 235,
    mileageCityKmpl: 11.8, mileageHighwayKmpl: 15.5, mileageCombinedKmpl: 13.7, fuelTankLitres: 60,
    lengthMm: 4500, widthMm: 1848, heightMm: 1616, wheelbaseMm: 2680, groundClearanceMm: 181, kerbWeightKg: 1670, bootSpaceLitres: 530,
    safetyRatingStars: 5, safetyRatingAgency: 'EURO NCAP', safetyRatingYear: 2022, airbagCount: 8,
    features: ['MMI Navigation Plus', 'Bang & Olufsen Sound', 'Panoramic Sunroof', 'Virtual Cockpit Plus', 'Matrix LED', 'Wireless Charging'],
    adasFeatures: ['Adaptive Cruise Assist', 'Lane Departure Warning', 'Side Assist', 'Pre Sense Rear'],
    tags: ['luxury-suv', 'german-luxury', 'awd', 'premium', 'quattro'],
    popularityScore: 640, colors: ['Glacier White', 'Mythos Black', 'District Green', 'Florett Silver'],
    images: [],
  },

  // ── More popular Indian market cars ────────────────────────────────────────
  {
    make: 'Maruti Suzuki', model: 'Ertiga', variant: 'ZXi Plus CNG', year: 2024,
    priceExShowroom: 1349000, priceOnRoad: 1530000,
    bodyType: 'minivan', segment: 'compact', fuelType: 'cng',
    transmission: 'manual', drivetrain: 'fwd', seatingCapacity: 7,
    engineDisplacementCc: 1462, powerBhp: 91, torqueNm: 122,
    mileageCityKmpl: 26.1, mileageHighwayKmpl: 28.4, mileageCombinedKmpl: 26.1, fuelTankLitres: 45,
    lengthMm: 4395, widthMm: 1735, heightMm: 1690, wheelbaseMm: 2740, groundClearanceMm: 180, kerbWeightKg: 1265, bootSpaceLitres: 135,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 2,
    features: ['Touchscreen', 'Auto AC', 'Reverse Camera', 'Wireless CarPlay', 'LED Headlights'],
    adasFeatures: [],
    tags: ['cng', '7-seater', 'lowest-running-cost', 'family-mpv', 'cng-mpv'],
    popularityScore: 700, colors: ['Primrose Yellow', 'Auburn Red', 'Oxford Blue', 'Pearl Arctic White'],
    images: [],
  },
  {
    make: 'Maruti Suzuki', model: 'Fronx', variant: 'Alpha Turbo AT', year: 2024,
    priceExShowroom: 1299000, priceOnRoad: 1480000,
    bodyType: 'crossover', segment: 'compact', fuelType: 'petrol',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 998, powerBhp: 100, torqueNm: 148,
    acceleration0to100Sec: 10.5, topSpeedKph: 170,
    mileageCityKmpl: 19.01, mileageHighwayKmpl: 21.5, mileageCombinedKmpl: 20.1, fuelTankLitres: 37,
    lengthMm: 3995, widthMm: 1765, heightMm: 1550, wheelbaseMm: 2520, groundClearanceMm: 190, kerbWeightKg: 1030, bootSpaceLitres: 308,
    safetyRatingStars: 2, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2024, airbagCount: 6,
    features: ['Head-Up Display', 'Sunroof', '9-inch Touchscreen', 'Wireless Charging', 'Auto AC', 'LED Headlights'],
    adasFeatures: [],
    tags: ['crossover', 'sporty', 'coupe-crossover', 'youth', 'stylish'],
    popularityScore: 740, colors: ['Earthen Brown', 'Splendid Silver', 'Sizzling Red', 'Midnight Black'],
    images: [],
  },
  {
    make: 'Hyundai', model: 'Grand i10 Nios', variant: 'Asta AMT', year: 2024,
    priceExShowroom: 799000, priceOnRoad: 915000,
    bodyType: 'hatchback', segment: 'economy', fuelType: 'petrol',
    transmission: 'amt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 1197, powerBhp: 83, torqueNm: 114,
    mileageCityKmpl: 20.7, mileageHighwayKmpl: 23.4, mileageCombinedKmpl: 21.8, fuelTankLitres: 37,
    lengthMm: 3805, widthMm: 1680, heightMm: 1520, wheelbaseMm: 2450, groundClearanceMm: 165, kerbWeightKg: 930, bootSpaceLitres: 260,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2020, airbagCount: 2,
    features: ['8-inch Touchscreen', 'Wireless CarPlay', 'Auto AC', 'Reverse Camera', 'LED DRLs'],
    adasFeatures: [],
    tags: ['budget-hatchback', 'first-car', 'city-car', 'fuel-efficient'],
    popularityScore: 670, colors: ['Typhoon Silver', 'Polar White', 'Starry Night', 'Fiery Red'],
    images: [],
  },
  {
    make: 'Tata', model: 'Tiago EV', variant: 'Long Range XZ Plus LUX', year: 2024,
    priceExShowroom: 1099000, priceOnRoad: 1250000,
    bodyType: 'hatchback', segment: 'electric', fuelType: 'electric',
    transmission: 'automatic', drivetrain: 'fwd', seatingCapacity: 5,
    powerBhp: 74, torqueNm: 114,
    acceleration0to100Sec: 11.5, topSpeedKph: 130,
    batteryKwh: 24, electricRangeKm: 315,
    lengthMm: 3769, widthMm: 1677, heightMm: 1536, wheelbaseMm: 2400, groundClearanceMm: 165, kerbWeightKg: 1157, bootSpaceLitres: 242,
    safetyRatingStars: 4, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2023, airbagCount: 4,
    features: ['10.25-inch Touchscreen', 'Wireless CarPlay', 'Auto AC', 'Wireless Charging', 'Connected Car'],
    adasFeatures: [],
    tags: ['affordable-ev', 'hatchback-ev', 'city-ev', 'budget-ev'],
    popularityScore: 750, colors: ['Daytona Grey', 'Pristine White', 'Midnight Black', 'Intensi-Teal'],
    images: [],
  },
  {
    make: 'Toyota', model: 'Camry', variant: 'Hybrid AT', year: 2024,
    priceExShowroom: 4699000, priceOnRoad: 5300000,
    bodyType: 'sedan', segment: 'luxury', fuelType: 'hybrid',
    transmission: 'cvt', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 2487, powerBhp: 218, torqueNm: 221,
    acceleration0to100Sec: 8.3, topSpeedKph: 180,
    mileageCityKmpl: 19.14, mileageHighwayKmpl: 21.5, mileageCombinedKmpl: 19.14, fuelTankLitres: 50,
    lengthMm: 4885, widthMm: 1840, heightMm: 1445, wheelbaseMm: 2825, groundClearanceMm: 155, kerbWeightKg: 1625, bootSpaceLitres: 493,
    safetyRatingStars: 5, safetyRatingAgency: 'EURO NCAP', safetyRatingYear: 2022, airbagCount: 9,
    features: ['JBL Sound', '10.5-inch Touchscreen', 'Panoramic Roof', 'Ventilated Seats', 'Toyota Safety Sense', 'Ambient Lighting'],
    adasFeatures: ['Pre-Collision System', 'Lane Departure Alert', 'Radar Cruise Control', 'Blind Spot Monitor'],
    tags: ['hybrid', 'luxury-sedan', 'executive', 'business-car', 'eco'],
    popularityScore: 600, colors: ['Platinum White Pearl', 'Silver Metallic', 'Attitude Black', 'Celestite Grey'],
    images: [],
  },
  {
    make: 'Kia', model: 'Sonet', variant: 'HTX Plus Turbo DCT', year: 2024,
    priceExShowroom: 1299000, priceOnRoad: 1480000,
    bodyType: 'suv', segment: 'economy', fuelType: 'petrol',
    transmission: 'dct', drivetrain: 'fwd', seatingCapacity: 5,
    engineDisplacementCc: 998, powerBhp: 118, torqueNm: 172,
    acceleration0to100Sec: 9.9, topSpeedKph: 170,
    mileageCityKmpl: 16.6, mileageHighwayKmpl: 19.4, mileageCombinedKmpl: 18.2, fuelTankLitres: 45,
    lengthMm: 3995, widthMm: 1790, heightMm: 1642, wheelbaseMm: 2500, groundClearanceMm: 211, kerbWeightKg: 1195, bootSpaceLitres: 392,
    safetyRatingStars: 3, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2022, airbagCount: 6,
    features: ['10.25-inch Touchscreen', 'Bose Sound', 'Sunroof', 'Wireless Charging', 'Wireless CarPlay', 'Air Purifier'],
    adasFeatures: ['Forward Collision Warning', 'Lane Keep Assist'],
    tags: ['compact-suv', 'turbo', 'feature-loaded', 'first-suv'],
    popularityScore: 730, colors: ['Imperial Blue', 'Aurora Black', 'Glacier White', 'Pewter Olive'],
    images: [],
  },
  {
    make: 'Ford', model: 'Endeavour', variant: 'Sport 4x4 AT', year: 2021,
    priceExShowroom: 3999000, priceOnRoad: 4520000,
    bodyType: 'suv', segment: 'full-size', fuelType: 'diesel',
    transmission: 'automatic', drivetrain: '4wd', seatingCapacity: 7,
    engineDisplacementCc: 1996, powerBhp: 210, torqueNm: 500,
    acceleration0to100Sec: 9.1, topSpeedKph: 180,
    mileageCityKmpl: 10.9, mileageHighwayKmpl: 14.2, mileageCombinedKmpl: 12.4, fuelTankLitres: 80,
    lengthMm: 4892, widthMm: 1860, heightMm: 1837, wheelbaseMm: 2850, groundClearanceMm: 225, kerbWeightKg: 2145, bootSpaceLitres: 445,
    safetyRatingStars: 5, safetyRatingAgency: 'EURO NCAP', safetyRatingYear: 2019, airbagCount: 7,
    features: ['SYNC 3', 'Sony Sound', 'Panoramic Sunroof', 'Terrain Management System', 'Wireless Charging', 'Adaptive Cruise'],
    adasFeatures: ['Adaptive Cruise Control', 'Pre-Collision Assist', 'Blind Spot Monitor', 'Lane Keep Assist'],
    tags: ['4wd', 'off-road', '7-seater', 'discontinued', 'full-size-suv'],
    popularityScore: 550, colors: ['White Platinum', 'Shadow Black', 'Chrome Blue', 'Moondust Silver'],
    images: [],
    discontinuedAt: new Date('2022-01-01'),
  },
  {
    make: 'Mahindra', model: 'BE 6', variant: 'Pack Three AWD', year: 2025,
    priceExShowroom: 2499000, priceOnRoad: 2820000,
    bodyType: 'suv', segment: 'electric', fuelType: 'electric',
    transmission: 'automatic', drivetrain: 'awd', seatingCapacity: 5,
    powerBhp: 282, torqueNm: 380,
    acceleration0to100Sec: 6.7, topSpeedKph: 200,
    batteryKwh: 79, electricRangeKm: 535,
    lengthMm: 4371, widthMm: 1900, heightMm: 1635, wheelbaseMm: 2775, groundClearanceMm: 207, kerbWeightKg: 2100, bootSpaceLitres: 455,
    safetyRatingStars: 5, safetyRatingAgency: 'GLOBAL NCAP', safetyRatingYear: 2025, airbagCount: 7,
    features: ['19.2-inch Touchscreen', 'HARMAN Sound', 'Vehicle to Load', 'Wireless Charging', 'ADAS Level 2+', 'Auto Park'],
    adasFeatures: ['Adaptive Cruise Control', 'Auto Emergency Braking', 'Lane Centering', 'Blind Spot Monitoring', 'Rear Collision Warning'],
    tags: ['electric', 'awd', 'performance-ev', 'future', 'made-in-india'],
    popularityScore: 860, colors: ['Tango Red', 'Stealth Black', 'Everest White', 'Galaxy Grey'],
    images: [],
    launchedAt: new Date('2025-02-01'),
  },
]

// ── Attach slugs ──────────────────────────────────────────────────────────────

const carsWithSlug = cars.map((car) => ({
  ...car,
  slug: slug(car.make, car.model, car.variant, car.year),
  images: [],
}))

// ── Reviews (realistic Indian owner reviews) ──────────────────────────────────

function makeReviews(carId: string, carSlug: string) {
  const pool = [
    {
      user: 'user_rahul_sharma',
      ratings: { overall: 5, comfort: 5, performance: 4, fuelEfficiency: 5, valueForMoney: 5, maintenance: 4 },
      title: 'Best decision of my life',
      body: 'Bought this 6 months ago and it has been an absolute joy to drive. Mileage is exactly as claimed. Service centre staff are helpful. Would highly recommend to anyone looking for a reliable daily driver.',
      pros: ['Excellent mileage', 'Low maintenance cost', 'Smooth ride quality'],
      cons: ['Rear seat a bit cramped', 'Average soundproofing'],
      ownershipMonths: 6, kmDriven: 12000, verified: true,
    },
    {
      user: 'user_priya_menon',
      ratings: { overall: 4, comfort: 4, performance: 3, fuelEfficiency: 4, valueForMoney: 4, maintenance: 5 },
      title: 'Great family car, minor niggles',
      body: 'This car has been with our family for 8 months. Comfortable for highway trips to Kerala and handles Bangalore traffic well. AC cools the cabin very fast. Some plastic quality could be better.',
      pros: ['Comfortable seats', 'Fast AC cooling', 'Easy to drive in traffic'],
      cons: ['Interior plastics feel average', 'Tyre noise on highways'],
      ownershipMonths: 8, kmDriven: 18000, verified: true,
    },
    {
      user: 'user_aakash_patel',
      ratings: { overall: 4, comfort: 3, performance: 5, fuelEfficiency: 3, valueForMoney: 4, maintenance: 3 },
      title: 'Punchy engine, fun to drive',
      body: 'If you want a spirited drive in this segment this is the one. Overtaking on highways is effortless. Fuel efficiency could be better if you drive with a heavy foot like me. Overall happy.',
      pros: ['Strong performance', 'Quick acceleration', 'Confident on highways'],
      cons: ['Real-world mileage is lower than claimed', 'Service cost a bit high'],
      ownershipMonths: 12, kmDriven: 25000, verified: false,
    },
    {
      user: 'user_deepika_nair',
      ratings: { overall: 5, comfort: 5, performance: 5, fuelEfficiency: 4, valueForMoney: 5, maintenance: 4 },
      title: 'Perfect car for Indian roads',
      body: 'Ground clearance is amazing. Went on a road trip to Coorg and the car handled all the bad roads without any issue. Feature list is great for the price point. Very happy with my purchase.',
      pros: ['High ground clearance', 'Great feature list', 'Premium feel inside'],
      cons: ['Slightly pricey on-road', 'Waiting period can be long'],
      ownershipMonths: 4, kmDriven: 9000, verified: true,
    },
    {
      user: 'user_suresh_kumar',
      ratings: { overall: 3, comfort: 3, performance: 3, fuelEfficiency: 4, valueForMoney: 3, maintenance: 2 },
      title: 'Average product, expected more',
      body: 'Have owned this for 18 months. After the first service the steering started feeling vague. Dealership took 3 visits to fix it. Mileage is decent but the overall quality has declined compared to older models.',
      pros: ['Good mileage', 'Easy to get service centres'],
      cons: ['Quality has gone down', 'Dealership service is poor in my city', 'Vague steering'],
      ownershipMonths: 18, kmDriven: 40000, verified: true,
    },
  ]

  return pool.map((r, i) => ({
    ...r,
    car: carId,
    user: `${r.user}_${carSlug.substring(0, 8)}_${i}`,
  }))
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function seed() {
  const MONGOOSE_OPTIONS = {
    dbName: 'cardeko',
    serverSelectionTimeoutMS: 10000,
    maxPoolSize: 5,
  }

  console.log('\n[seed] Connecting to MongoDB...')
  await mongoose.connect(env.MONGODB_URI, MONGOOSE_OPTIONS)
  console.log(`[seed] Connected → ${mongoose.connection.host} / ${mongoose.connection.db?.databaseName}\n`)

  // ── Wipe existing data ──────────────────────────────────────────────────────
  console.log('[seed] Clearing existing cars and reviews...')
  await Car.deleteMany({})
  await Review.deleteMany({})
  console.log('[seed] Cleared.\n')

  // ── Insert cars ─────────────────────────────────────────────────────────────
  console.log(`[seed] Inserting ${carsWithSlug.length} cars...`)
  const inserted = await Car.insertMany(carsWithSlug, { ordered: false })
  console.log(`[seed] Inserted ${inserted.length} cars.\n`)

  // ── Insert reviews (2-3 per car for the first 20 cars) ─────────────────────
  const reviewTargets = inserted.slice(0, 20)
  let totalReviews = 0

  for (const car of reviewTargets) {
    const reviews = makeReviews(String(car._id), car.slug).slice(0, 3)
    await Review.insertMany(reviews, { ordered: false })
    totalReviews += reviews.length
  }

  console.log(`[seed] Inserted ${totalReviews} reviews across ${reviewTargets.length} cars.\n`)

  // ── Summary ─────────────────────────────────────────────────────────────────
  const carCount = await Car.countDocuments()
  const reviewCount = await Review.countDocuments()
  console.log(`[seed] ✓ Database seeded successfully`)
  console.log(`       Cars    : ${carCount}`)
  console.log(`       Reviews : ${reviewCount}\n`)

  await mongoose.disconnect()
  console.log('[seed] Disconnected. Done.\n')
}

seed().catch(err => {
  console.error('[seed] Fatal error:', err)
  process.exit(1)
})
